# Generated by Django 3.2.23 on 2023-12-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('techs', models.CharField(max_length=200)),
                ('demo', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('data_science', models.BooleanField(default=False)),
            ],
        ),
    ]
