# Generated by Django 3.2.23 on 2023-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skill_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_text',
            field=models.TextField(default='nice to work with kabir'),
            preserve_default=False,
        ),
    ]
