# Generated by Django 3.2.23 on 2023-12-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon_name',
            field=models.CharField(default='book', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
